import React,{useState} from 'react';
import {ArrowRight,Search,BookOpen,RotateCcw,Check,Eye,Microscope,Leaf,Camera,Lightbulb} from 'lucide-react';
import {Cell,Photo,Motif} from './Art';
import {organisms,lessons} from './data';
import {ScaleLab} from './Activities';
import {DesignHero,SpecimenVisual,ToolVisual,TopicTrail} from './DesignSystem';

function ConceptDetails({page}){const [key,setKey]=useState('');const l=lessons[page];return <div className="concept-details"><div className="keyword-row">{Object.keys(l.keys).map(k=><button key={k} aria-expanded={key===k} className={key===k?'active':''} onClick={()=>setKey(key===k?'':k)}>{k}<span>＋</span></button>)}</div>{key&&<p className="keyword-note" role="status">{l.keys[key]}</p>}<details><summary>閱讀完整概念</summary><p>{l.text}</p><small>{l.source}・依教材改寫</small></details></div>;}

export function Intro({onComplete,completed,navigate,response}){
 const [prediction,setPrediction]=useState(response?.prediction||''),[zoom,setZoom]=useState(response?.zoom??(completed?100:0)),[observed,setObserved]=useState(!!completed),[reason,setReason]=useState(completed?'details':''),[checked,setChecked]=useState(false);
 function confirmAnswer(){if(completed){navigate(2);return;}if(!prediction||!observed||!reason)return;setChecked(true);if(reason==='details')onComplete({prediction,zoom,reason});}
 const scene=zoom<34?0:zoom<67?1:2;
 function observe(v){setZoom(v);if(v>=76)setObserved(true);}
 return <><section className="intro-scene"><div className="intro-copy"><span className="eyebrow">探索前的第一個問題</span><h1>同一個世界，<br/>為什麼看見<br/>不一樣的面貌？</h1><p>改變觀察尺度，就能發現原本看不見的線索。</p><p className="hand-note">世界沒有變，<br/>是我們的視角變了。</p></div><div className="intro-worlds">{[['一座池塘',[384,185,250,234],'看見生物與環境'],['一滴池水',[713,247,112,107],'從環境取一個小小樣本'],['微觀世界',[906,211,195,190],'看見外形與細胞構造']].map(([title,region,desc],i)=><React.Fragment key={title}><button aria-pressed={scene===i} className={'world-circle '+(scene===i?'active':'')} onClick={()=>observe(i*50)}><h2>{title}</h2><Photo page={1} region={region} label={title}/><p>{desc}</p></button>{i<2&&<ArrowRight className="world-arrow"/>}</React.Fragment>)}<div className="world-scale"><span>巨觀<br/><small>較大尺度</small></span><button aria-label="縮小觀察尺度" onClick={()=>observe(Math.max(0,zoom-25))}>−</button><input aria-label="改變觀察尺度" type="range" min="0" max="100" value={zoom} onChange={e=>observe(+e.target.value)}/><button aria-label="放大觀察尺度" onClick={()=>observe(Math.min(100,zoom+25))}>＋</button><span>微觀<br/><small>較小尺度</small></span></div><p className="scene-observation" aria-live="polite">{['先看整體：池塘與周圍的生物如何相互關聯？','再取樣本：小小一滴水，也可能有許多生命。','看清細部：可以辨認不同外形，以及纖毛、鞭毛等構造。'][scene]}</p></div></section>
 <section className="panel intro-investigation"><div><h2>先猜猜，再觀察</h2><p>放大同一滴池水後，會出現哪些新資訊？</p><div className="prediction-cards">{[['details','更多形態與構造','可能辨認生物的外形與細部',[751,1030,133,96]],['larger','只是畫面變大','只會讓同一個小點看起來更大',[496,1034,196,87]]].map(([id,title,text,region])=><button key={id} disabled={completed} aria-pressed={prediction===id} className={prediction===id?'selected':''} onClick={()=>setPrediction(id)}><Photo page={1} region={region} label={title}/><span className="prediction-check">{prediction===id?'✓':'○'}</span><strong>{title}</strong><span>{text}</span></button>)}</div><div className="intro-answer"><label>觀察後，我認為<select aria-label="觀察後，我認為" value={reason} disabled={completed} onChange={e=>{setReason(e.target.value);setChecked(false);}}><option value="">選擇你的解釋</option><option value="details">改變工具與尺度，可以取得不同層次的資訊。</option><option value="grow">生物在放大時真的變大了。</option></select></label>{checked&&reason==='grow'&&<p className="feedback incorrect" role="alert">改變的是觀察畫面；生物的實際大小不會因此改變。</p>}{completed&&<p className="feedback correct" role="status"><strong>答案確認正確。</strong>改變觀察工具與尺度，能看見不同層次的形態與構造；生物的實際大小不會因此改變。</p>}<button className="primary" disabled={!completed&&(!prediction||!observed||!reason)} onClick={confirmAnswer}>{completed?<>前往觀察尺度<ArrowRight size={18}/></>:<>確認答案<ArrowRight size={18}/></>}</button>{completed&&<small role="status">導讀答案已確認，已解鎖下一頁。</small>}{!completed&&!observed&&<small>記下預測後，操作上方尺度滑桿到「微觀」，再修正解釋。</small>}</div></div><aside className="inquiry-method"><h2>科學探究這樣做</h2>{[[Lightbulb,'先提出預測','根據你的經驗和想法，猜猜會看到什麼？'],[Microscope,'操作找證據','透過觀察、測量或查資料，找出證據。'],[BookOpen,'修正你的解釋','比較預測與證據，調整想法，建立解釋。']].map(([Icon,t,d],i)=><article key={t}><b>0{i+1}</b><span><Icon size={32}/></span><div><h3>{t}</h3><p>{d}</p></div></article>)}<p className="hand-note">好奇心是科學的起點，<br/>觀察讓我們更接近真相。</p><p className="hint">此處呈現不同觀察層次；數位放大本身不會增加真實儀器的解析力。</p></aside></section>
 <section className="panel intro-roadmap"><h2>這趟旅程，你將學會</h2><TopicTrail/></section></>;
}

export function ObservationLab(){const [tab,setTab]=useState(0),[tool,setTool]=useState(0),[gap,setGap]=useState(4),[magnify,setMagnify]=useState(false),[snapshot,setSnapshot]=useState('');
 const labels=tab===1?['池塘環境','一滴池水','微小生物']:['麵包整體','黴斑局部','黴菌細部'];
 return <><section className="observation-workbench"><aside className="panel observation-concept"><h2>微觀與巨觀</h2><p><strong>微觀尺度</strong>指肉眼不易看見的微小事物；<strong>巨觀尺度</strong>指肉眼可見或更大的事物。</p><div className="tool-selector">{['肉眼','放大鏡','複式顯微鏡'].map((t,i)=><button key={t} aria-pressed={tool===i} className={tool===i?'active':''} onClick={()=>setTool(i)}><ToolVisual name={t}/><strong>{t}</strong><small>{['能看整體，難辨細部。','放大局部的外觀特徵。','觀察細胞及微小構造。'][i]}</small></button>)}</div><p className="observation-note" aria-live="polite">{['先掌握整體，再決定要研究哪一個局部。','放大局部會減少視野範圍；看清的細節仍受工具能力限制。','觀察細部需要足夠放大與解析能力；也要適當製備樣本。'][tool]}</p><ConceptDetails page={2}/></aside>
 <div className="panel observation-stage"><div className="observation-tabs">{['麵包與黴菌','池水與生物','肉眼的極限'].map((s,i)=><button key={s} aria-pressed={tab===i} className={tab===i?'active':''} onClick={()=>{setTab(i);setSnapshot('');}}>{i===0?<Leaf size={20}/>:i===1?<Microscope size={20}/>:<Eye size={20}/>} {s}</button>)}</div>
 {tab<2?<div className="connected-scenes">{labels.map((label,i)=><button key={label} aria-pressed={tool===i} className={'scene-card '+(tool===i?'active':'')} onClick={()=>setTool(i)}><strong>{label}</strong>{tab===0?<Photo page={2} region={[[403,389,213,208],[626,391,200,195],[876,392,223,186]][i]} label={label}/>:<Photo page={1} region={[[387,186,247,234],[713,247,112,107],[906,211,195,190]][i]} label={label}/>}<small>{['整體的形狀與分布','局部的特徵','更細微的構造'][i]}</small></button>)}</div>:<div className="limit-experiment"><h3>點的間距，改變你的判斷</h3><div className="dot-board" style={{backgroundSize:`${magnify?gap*7:gap*2.3}px ${magnify?gap*7:gap*2.3}px`}}/><label>點的間距<input aria-label="點的間距" type="range" min="1" max="10" value={gap} onChange={e=>setGap(+e.target.value)}/></label><button className="secondary" onClick={()=>setMagnify(!magnify)}>{magnify?'回到整體觀察':'放大觀察'}</button><p>兩點太接近時，看起來可能連成一片。放大畫面與增加儀器解析力是不同的事。</p></div>}
 <div className="observation-toolbar"><span>整體</span><input aria-label="觀察尺度" type="range" min="0" max="2" step="1" value={tool} onChange={e=>setTool(+e.target.value)}/><span>細部</span><button className="secondary" onClick={()=>setSnapshot(`已記錄：${tab===2?'點陣觀察':labels[tool]}。使用${['肉眼','放大鏡','複式顯微鏡'][tool]}，注意觀察目的與細節是否相符。`)}><Camera size={18}/>拍下來</button></div>{snapshot&&<p className="capture-note" role="status"><Check size={17}/>{snapshot}</p>}</div></section>
 <section className="panel resolution-compare"><div><h2>肉眼能分辨多小的間距？</h2><p>兩張點陣圖的點大小相同、間距不同。從約 25 公分的距離觀察，哪些點容易連成一片？</p></div><figure><figcaption>間距較小</figcaption><div className="dots-close"/><span className="dot-magnifier close"/></figure><figure><figcaption>間距較大</figcaption><div className="dots-apart"/><span className="dot-magnifier apart"/></figure><div className="distance-figure"><Photo page={2} region={[883,682,277,152]} label="眼睛與點陣約 25 公分的觀察距離"/><small>教材以約 0.1 mm 點距說明肉眼分辨情境；螢幕未校準，不能用來測視力。</small></div></section></>;
}

const specimens=[['氫原子','奈米 nm','原子尺度極微小，這裡以模型示意。','atom'],['流感病毒','奈米 nm','病毒的大小通常以奈米描述。','virus'],['植物細胞','微米 μm','細胞大小常以微米表示，並非所有細胞一樣大。','cell'],['沙粒','毫米 mm','小顆粒常用毫米描述，仍須按實際尺寸選擇。','seed'],['綠豆幼苗','公分 cm','幼苗長高後，用公分能方便記錄。','sprout'],['人類','公尺 m','身高也可用公分；選擇易讀、方便比較的數值。','person'],['臺灣中央山脈','公里 km','大型地形的延伸距離常以公里描述。','mountain'],['銀河系','光年','光年用於極大的距離，不是時間或速度。','galaxy']];
export function UnitLab(){const [picked,setPicked]=useState(2),[number,setNumber]=useState('1'),[from,setFrom]=useState('m'),[to,setTo]=useState('μm'),[growth,setGrowth]=useState('mm');const factors={km:1000,m:1,cm:.01,mm:.001,'μm':1e-6,nm:1e-9};const converted=Number(number)*factors[from]/factors[to];return <><section className="unit-concept"><BookOpen/><p>物體的大小不同，適合使用的長度單位也不同。</p><div>{['奈米 nm','微米 μm','毫米 mm','公分 cm','公尺 m','公里 km','光年'].map((s,i)=><button key={s} onClick={()=>setPicked([0,2,3,4,5,6,7][i])}>{s}</button>)}</div></section>
 <section className="panel scale-gallery"><div className="section-heading"><h2>尺度探索：點選物體，看它適合用什麼單位</h2><small>尺度示意，非等距實物排列。</small></div><div className="specimen-strip">{specimens.map(([name,unit,desc,art],i)=><button key={name} aria-pressed={picked===i} className={picked===i?'active':''} onClick={()=>setPicked(i)}><SpecimenVisual type={art}/><strong>{name}</strong><small>{unit}</small></button>)}</div><div className="ruler-line"/><label className="scale-picker"><span>−</span><input aria-label="選擇物體尺度" type="range" min="0" max="7" step="1" value={picked} onChange={e=>setPicked(+e.target.value)}/><span>＋</span></label><p className="unit-discovery" aria-live="polite"><strong>{specimens[picked][0]}・{specimens[picked][1]}</strong>{specimens[picked][2]}</p></section>
 <div className="two-col unit-workbenches"><section className="panel"><h2>單位轉換工作臺</h2><p>在不同單位之間轉換，幫助你用更合適的語言描述世界。</p><div className="formula">1 m ＝ 1,000 mm ＝ 1,000,000 μm ＝ 1,000,000,000 nm</div><div className="unit-converter"><label>數值<input aria-label="換算數值" type="number" min="0" value={number} onChange={e=>setNumber(e.target.value)}/></label><label>原單位<select value={from} onChange={e=>setFrom(e.target.value)}>{Object.keys(factors).map(u=><option key={u}>{u}</option>)}</select></label><ArrowRight/><label>換成<select aria-label="換成單位" value={to} onChange={e=>setTo(e.target.value)}>{Object.keys(factors).map(u=><option key={u}>{u}</option>)}</select></label></div><output className="big-output">{number===''||!Number.isFinite(converted)||Number(number)<0?'請輸入有效長度':new Intl.NumberFormat('en-US',{maximumSignificantDigits:10}).format(converted)} <small>{to}</small></output><details><summary>用科學記號，讀懂很多個 0</summary><p>1,000,000 可以寫成 10⁶；1 奈米＝10⁻⁹ 公尺。單位越小，表示同一長度的數值越大。</p></details></section>
 <section className="panel growth"><h2><Leaf size={25}/> 綠豆真的長大了嗎？</h2><p>同一棵綠豆從發芽到長大，用相同單位才好比較。</p><div className="growth-photos"><figure><span>第 1 天</span><Photo page={3} region={[628,792,163,123]} label="發芽綠豆與尺"/><strong>{growth==='mm'?'5 mm':'0.5 cm'}</strong></figure><div><ArrowRight size={40}/><p>3 cm＝30 mm</p><div className="segmented">{['mm','cm'].map(u=><button key={u} className={growth===u?'active':''} aria-pressed={growth===u} onClick={()=>setGrowth(u)}>用 {u} 記錄</button>)}</div></div><figure><span>第 5 天</span><Photo page={3} region={[972,792,157,126]} label="綠豆幼苗與尺"/><strong>{growth==='mm'?'30 mm':'3 cm'}</strong></figure></div><details><summary>觀察後，核對你的比較</summary><p>長度增加 25 mm，最後長度是原來的 6 倍。更換單位時，照片與物體本身都不會變大。</p></details></section></div><ConceptDetails page={3}/></>;}

export function PondLab(){const [mag,setMag]=useState(1),[focus,setFocus]=useState(5),[light,setLight]=useState(85),[xy,setXY]=useState([70,40]),[movement,setMovement]=useState('目標位於右下方。移動玻片，讓它回到中央。'),[species,setSpecies]=useState(5),[notes,setNotes]=useState([]),[all,setAll]=useState(false);function move(dx,dy,label){setXY(([x,y])=>[Math.max(-150,Math.min(150,x-dx)),Math.max(-95,Math.min(95,y-dy))]);setMovement(`玻片往${label}，影像反方向移動。`);}const selected=organisms[species];return <><section className="pond-workbench"><aside className="panel preparation"><h2>先找到，再看清</h2><p>正確的製片步驟，能讓池水中的生物清楚呈現。</p><div className="steps">{[['滴池水','用滴管吸取池水，滴在載玻片上。',[43,330,148,86]],['蓋玻片','輕蓋蓋玻片，吸去多餘水分。',[221,330,147,84]],['低倍尋找','先用低倍率尋找生物，調整光線與焦距。',[40,496,151,86]],['高倍觀察','找到目標並置中後，再換高倍率仔細觀察。',[222,498,146,84]]].map(([t,s,r],i)=><article key={t}><span>{i+1}</span><Photo page={5} region={r} label={t}/><h3>{t}</h3><p>{s}</p></article>)}</div><p className="hand-note">觀察影像會上下顛倒、左右相反。</p></aside>
 <section className="panel microscope-lab"><div className="scope-controls"><Photo page={5} region={[411,264,165,187]} label="複式顯微鏡"/><div className="segmented">{[1,2].map(m=><button key={m} aria-pressed={mag===m} className={mag===m?'active':''} onClick={()=>setMag(m)}>{m===1?'低倍率':'高倍率'}</button>)}</div><label>光源亮度<input aria-label="光源亮度" type="range" min="35" max="100" value={light} onChange={e=>setLight(+e.target.value)}/></label><label>對焦<input aria-label="顯微鏡對焦" type="range" min="0" max="10" value={focus} onChange={e=>setFocus(+e.target.value)}/></label><p className="hint">載物台移動</p><div className="direction-grid">{[[-20,-20,'左上'],[0,-20,'上'],[20,-20,'右上'],[-20,0,'左'],[0,0,'重設'],[20,0,'右'],[-20,20,'左下'],[0,20,'下'],[20,20,'右下']].map(([x,y,t],i)=><button key={t} aria-label={`移動玻片：${t}`} onClick={()=>t==='重設'?(setXY([70,40]),setMag(1),setMovement('已將目標重設到右下方。')):move(x,y,t)}>{['↖','↑','↗','←','⌂','→','↙','↓','↘'][i]}</button>)}</div></div>
 <div className="scope-area"><div className="microscope-field" style={{filter:`brightness(${light}%)`}}><div className="pond-water"><Photo page={0} region={[723,825,186,148]} label="池水視野背景示意" fit="slice"/></div><div className="micro-organism" style={{transform:`translate(${xy[0]*mag}px,${xy[1]*mag}px) scale(${mag})`,filter:`blur(${Math.abs(5-focus)*.7}px)`}}><SpecimenVisual type={selected[3]}/></div><span className="crosshair">＋</span><span className="scope-caption">構造與操作方向示意</span></div><div className={`observation-note ${Math.abs(xy[0])<=12&&Math.abs(xy[1])<=12?'correct':''}`} aria-live="polite">{Math.abs(xy[0])<=12&&Math.abs(xy[1])<=12?'目標已移到中央！現在試試高倍率。':movement}</div><div className="notebook-strip"><SpecimenVisual type={selected[3]}/><div><strong>我的觀察紀錄・{selected[0]}</strong><div className="chips">{['外形','移動方式','細胞構造'].map(n=><button key={n} aria-pressed={notes.includes(n)} className={notes.includes(n)?'active':''} onClick={()=>setNotes(notes.includes(n)?notes.filter(s=>s!==n):[...notes,n])}>{notes.includes(n)&&<Check size={14}/>} {n}</button>)}</div><p>{selected[2]}</p></div></div></div></section></section>
 <section className="panel species-section"><div className="section-heading"><div><h2>池水中的常見生物</h2><p>每一種都在池水中扮演重要角色。點選，換個對象觀察。</p></div><button className="text-button" aria-expanded={all} onClick={()=>setAll(!all)}>{all?'收合完整圖鑑':'查看完整圖鑑'}<ArrowRight size={17}/></button></div><div className="organism-gallery">{(all?organisms.map((_,i)=>i):[0,1,5,6]).map(i=>{const [name,category,desc,art]=organisms[i];return <button key={name} className={species===i?'active':''} aria-pressed={species===i} onClick={()=>{setSpecies(i);setNotes([]);setXY([0,0]);}}><SpecimenVisual type={art}/><div><strong>{name}</strong><small>{category}生物</small><p>{desc}</p><span className="circle-arrow"><ArrowRight size={16}/></span></div></button>;})}</div>{all&&<p className="hint">11 種代表的構造示意，各圖不是同一比例。藍菌屬細菌；圖像須搭配特徵比對。</p>}</section><ConceptDetails page={5}/></>;}

const bioCases=[{name:'蓮葉的自潔',title:'為什麼蓮葉總是乾乾淨淨？',phenomenon:'水滴在葉面滾動，並帶走髒汙。',structure:'葉面有微小突起，表面覆有防水角質。',invention:'防水、抗汙的塗料。',region:[600,122,582,426],images:[[45,602,268,107],[370,602,284,109],[715,602,248,109]]},{name:'芒刺的鉤',title:'小小芒刺，為什麼能沾住衣服？',phenomenon:'芒刺容易沾在衣服與動物毛髮上。',structure:'前端的鉤狀構造能勾住纖維。',invention:'鉤面與毛面組合的魔鬼氈。',region:[44,878,520,122],images:[[44,878,144,122],[186,883,118,115],[360,879,200,120]]},{name:'壁虎的足底',title:'壁虎如何攀附平滑的表面？',phenomenon:'壁虎能在平滑、垂直的表面攀爬。',structure:'足底剛毛與細微分支，能與表面充分接觸。',invention:'可重複黏貼的仿生膠帶。',region:[615,878,526,122],images:[[615,878,151,122],[767,887,139,111],[1010,881,129,117]]}];
export function BioLab(){const [tab,setTab]=useState(0),[layer,setLayer]=useState(0),[wax,setWax]=useState(true),[bumps,setBumps]=useState(true),[trial,setTrial]=useState(false);const b=bioCases[tab];return <><section className={'bio-hero bio-hero-'+tab}><DesignHero page={6}><div className="tabs">{bioCases.map((c,i)=><button key={c.name} aria-pressed={tab===i} className={tab===i?'active':''} onClick={()=>{setTab(i);setLayer(0);}}><Leaf size={19}/>{c.name}</button>)}</div><div className="bio-explanation"><h2>{b.title}</h2><p>{b.phenomenon}<br/>{b.structure}<br/>科學家參考這種構造，設計{b.invention}</p></div></DesignHero>{tab>0&&<Photo className="bio-alternate" page={6} region={b.region} label={b.name+'的構造與應用'}/>}</section>
 <section className="causal-chain photo-chain">{[['巨觀現象',b.phenomenon,Eye],['微觀證據',b.structure,Microscope],['仿生發明',b.invention,Leaf]].map(([name,text,Icon],i)=><button key={name} aria-pressed={layer===i} className={layer===i?'active':''} onClick={()=>setLayer(i)}><h3><Icon size={23}/>{name}</h3><Photo page={6} region={b.images[i]} label={name}/><p>{text}</p>{i<2&&<ArrowRight className="chain-arrow"/>}</button>)}</section><p className="chain-reading" aria-live="polite"><strong>{['先觀察現象','再用構造解釋','把原理用在設計'][layer]}</strong>：{[b.phenomenon,b.structure,b.invention][layer]}</p>
 <section className="bio-comparisons"><h2>微小構造，連接生活發明</h2><div>{bioCases.slice(1).map((c,i)=><button key={c.name} className="panel" onClick={()=>{setTab(i+1);setLayer(1);}}><h3>{i===0?'芒刺 → 魔鬼氈':'壁虎足底 → 仿生膠帶'}</h3><Photo page={6} region={c.region} label={c.name+'與仿生發明'}/><p>{c.structure}<br/>科學家由此發想，發展{c.invention}</p><span className="text-button">對照這個案例<ArrowRight size={16}/></span></button>)}</div></section>
 <details className="surface-experiment"><summary><Lightbulb size={21}/> 延伸實驗：只有凹凸，能完整解釋自潔嗎？</summary><section className="panel surface-lab"><div><h2>一次改一個條件</h2><p>比較模型中的表面構造與防水性，觀察水滴行為。</p><label className="switch"><input type="checkbox" checked={bumps} onChange={e=>{setBumps(e.target.checked);setTrial(false);}}/>微小突起</label><label className="switch"><input type="checkbox" checked={wax} onChange={e=>{setWax(e.target.checked);setTrial(false);}}/>防水角質</label><button className="primary" onClick={()=>setTrial(true)}>滴水，觀察<ArrowRight size={17}/></button></div><div><div className={`surface-demo ${bumps?'bumpy':''} ${wax?'waxy':''} ${trial?'running':''} ${trial&&wax&&bumps?'clean':''}`}><div className="water-drop"/><div className="dirt"><i/><i/><i/></div><div className="surface"/></div><p className="observation-note" aria-live="polite">{!trial?'先設定表面，再滴水觀察。':wax&&bumps?'兩個條件都具備，模型中的水滴容易滾動，帶走髒汙。':wax?'具有防水性，但缺少微小突起，不能把效果直接視為完整蓮葉自潔。':'只有突起不能保證自潔。還需要考慮表面的防水性。'}</p><p className="hint">這是比較條件的概念模型，不表示所有材料都有相同效果。</p></div></section></details><ConceptDetails page={6}/></>;}

export function Activities({page}){return page===2?<ObservationLab/>:page===3?<UnitLab/>:page===4?<ScaleLab/>:page===5?<PondLab/>:<BioLab/>;}
