import {useCloudLeaderboard} from './useCloudLeaderboard';
import React,{useState,useEffect,useRef} from 'react';
import {Search,Ruler,ArrowRight,ArrowLeft,Home,Check,Lock,Map as MapIcon,BookOpen,Leaf,Microscope,Trophy,Gamepad2,LogOut,X,Download,ShieldCheck,RotateCcw,Menu,ChevronRight} from 'lucide-react';
import {pages,lessons,questions,assessment,designFiles} from './data';
import {newSession,STORAGE_KEY,submitPractice,learningTotal,csvCell} from './engine';
import {Photo,Motif} from './Art';
import {Activities,Intro} from './ActivitiesRev';
import {DesignHero,HeroArt,Landscape,ReviewTopics} from './DesignSystem';
import {Results} from './ResultsRev';
import {Practice} from './Questions';
import {Assessment,Challenge} from './AssessmentGames';
import {SortingGame} from './SortingRev';
import {pageCompletion,lastUnlockedPage} from './progression';
import {GAS_ENDPOINT} from './sync-config';
import {scoreSnapshot,shouldSync,enqueueScore,flushScoreQueue} from './score-sync';
function initialDatabase(){try{const raw=JSON.parse(localStorage.getItem(STORAGE_KEY));if(raw?.version===4&&raw.sessions?.[raw.active]?.solved){if(raw.practiceRevision!==2){for(const session of Object.values(raw.sessions)){if(!session.solved?.s4&&session.attempts)delete session.attempts.s4;}raw.practiceRevision=2;}return raw;}}catch{}const s=newSession();return{version:4,practiceRevision:2,active:s.id,sessions:{[s.id]:s}};}
const sameIdentity=(a,b)=>a&&b&&['classroom','seat','name'].every(k=>a[k]===b[k]);
function Logo(){return <span className="logo"><span className="logo-symbol"><Search size={37} strokeWidth={1.7}/><Ruler size={20}/></span><span>尺度探索站<small>從不同的尺度，看見更大的世界</small></span></span>;}
function Modal({title,children,onClose,wide=false}){const ref=useRef();useEffect(()=>{ref.current.showModal();},[]);return <dialog ref={ref} className={wide?'wide':''} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="關閉視窗" onClick={onClose}><X/></button></div>{children}</dialog>;}
function HomePage({session,start,onIdentityEditing,navigate,restart,canVisit}){const [identity,setIdentity]=useState(session.identity||{classroom:'',seat:'',name:''});function update(k,v){setIdentity({...identity,[k]:v});onIdentityEditing();}return <><section className="home-hero"><HeroArt page={0}/><div className="home-copy"><span className="eyebrow">從巨觀到微觀，重新認識世界</span><h1>世界有多大？<br/>換個尺度，答案就不同。</h1><p>從一片葉子、一滴池水出發，<br/>學會觀察、比較與推理。</p><div className="hero-tags"><span><Leaf size={17}/>5 個核心任務</span><span><BookOpen size={17}/>約 2 節課探索</span><span>可分次完成</span></div><p className="hand-note">小小的事物，也能打開大大的世界。</p></div></section><section className="panel identity-panel"><div><h2>準備好，開始探索</h2><p>進度保存在這個瀏覽器，可稍後繼續。</p>{session.identity&&<button className="text-button" onClick={restart}><RotateCcw size={15}/>以相同身分重新學習</button>}</div><form onSubmit={e=>{e.preventDefault();start({...identity,seat:identity.seat.trim(),name:identity.name.trim(),classroom:identity.classroom.trim()});}}><label>班級<input required maxLength={20} placeholder="例如：701" value={identity.classroom} onChange={e=>update('classroom',e.target.value)}/></label><label>座號<input required inputMode="numeric" pattern="[0-9]{1,3}" maxLength={3} placeholder="例如：01" value={identity.seat} onChange={e=>update('seat',e.target.value)}/></label><label>姓名<input required maxLength={30} placeholder="輸入姓名" value={identity.name} onChange={e=>update('name',e.target.value)}/></label><button className="primary" disabled={!identity.name.trim()||!identity.classroom.trim()||!/^\d{1,3}$/.test(identity.seat)}>{sameIdentity(session.identity,identity)?'繼續我的探索':'開始我的探索'}<ArrowRight size={18}/></button></form></section><div className="section-heading"><div><h2>這趟旅程，你將學會</h2></div><p>尺度不只是數字，<br/>更是一種看待世界的方法。</p></div><section className="course-cards">{[2,3,4,5,6].map((p,i)=><button key={p} disabled={!canVisit(p)} onClick={()=>navigate(p)}><span className="course-card-title"><b>0{i+1}</b>{['觀察尺度','選對單位','讀懂比例尺','探索池水','仿生設計'][i]}</span><Photo page={0} region={[[33,823,204,153],[264,823,201,153],[495,823,192,153],[720,823,197,153],[950,823,194,153]][i]} label={pages[p].name}/><p>{lessons[p].goal}</p><span className="circle-arrow"><ArrowRight size={19}/></span></button>)}</section><div className="journey-strip"><span><Leaf/>先觀察</span><ArrowRight/><span><Microscope/>動手探索</span><ArrowRight/><span><BookOpen/>練習修正</span><ArrowRight/><span><Trophy/>挑戰應用</span></div></>;}
export default function App(){const [db,setDb]=useState(initialDatabase),[requestedPage,setPage]=useState(()=>Math.max(0,Math.min(10,Number(location.hash.replace('#page-',''))||0))),[modal,setModal]=useState(null),[teacher,setTeacher]=useState(false),[teacherSession,setTeacherSession]=useState(()=>newSession()),[password,setPassword]=useState(''),[passwordError,setPasswordError]=useState(''),[toast,setToast]=useState(''),[saveError,setSaveError]=useState(false),[syncStatus,setSyncStatus]=useState('idle'),[reportClass,setReportClass]=useState(''),[reportTopic,setReportTopic]=useState('all'),[reportSession,setReportSession]=useState('all');const session=teacher?teacherSession:db.sessions[db.active];const navRef=useRef();const done=pageCompletion(session),unlocked=teacher?10:lastUnlockedPage(done);const page=Math.min(Math.floor(requestedPage),unlocked);const canVisit=p=>p<=unlocked;
 useEffect(()=>{if(page!==requestedPage){setPage(page);location.replace(`#page-${page}`);}},[page,requestedPage]);
 useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(db));setSaveError(false);}catch{setSaveError(true);}},[db]);
 useEffect(()=>{const fn=()=>{setPage(Math.max(0,Math.min(10,Number(location.hash.replace('#page-',''))||0)));};window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn);},[]);
 useEffect(()=>{document.title=pages[page].name+'｜尺度探索站';navRef.current?.querySelector('[aria-current="page"]')?.scrollIntoView({block:'nearest',inline:'center'});},[page]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(timer);},[toast]);
 function navigate(p,target=session){const limit=teacher?10:lastUnlockedPage(pageCompletion(target));if(p>limit){setToast('請先完成「'+pages[limit].name+'」的所有題目與指定活動。');setModal(null);return;}setPage(p);location.hash=`page-${p}`;setModal(null);window.scrollTo({top:0,behavior:'instant'});}
 function update(fn){if(teacher)setTeacherSession(s=>fn(s));else setDb(prev=>{const next={...fn(prev.sessions[prev.active]),updatedAt:new Date().toISOString()};return{...prev,sessions:{...prev.sessions,[prev.active]:next}};});}
 function start(identity){if(sameIdentity(session.identity,identity)){navigate(1);return;}const s=newSession(identity);if(teacher)setTeacherSession(s);else setDb(prev=>({...prev,active:s.id,sessions:{...prev.sessions,[s.id]:s}}));navigate(1,s);}
 function clearForEditing(){if(!session.identity)return;const s=newSession();if(teacher)setTeacherSession(s);else setDb(prev=>({...prev,active:s.id,sessions:{...prev.sessions,[s.id]:s}}));}
 function submit(q,value){const next=submitPractice(session,q,value);if(next===session)return;update(()=>next);const last=next.events.at(-1);setToast(`${last.correct?'答對 ＋'+last.points+' 分':'本題 ＋0 分，讀解析後再試一次'} · 學習總分 ${learningTotal(next)} / 75${teacher?'（教師預覽）':''}`);}

 const percent=Math.round(done.slice(1).filter(Boolean).length/10*100);
 useEffect(()=>{if(teacher||navigator.webdriver||!shouldSync(session))return;enqueueScore(scoreSnapshot(session,percent));let active=true;setSyncStatus('syncing');const send=()=>flushScoreQueue(GAS_ENDPOINT).then(result=>{if(active)setSyncStatus(result.pending?'pending':'synced');}).catch(()=>{if(active)setSyncStatus('pending');});send();window.addEventListener('online',send);return()=>{active=false;window.removeEventListener('online',send);};},[teacher,session.id,session.updatedAt,percent]);
 const ranking=useCloudLeaderboard(page===9,`${syncStatus}:${session.updatedAt}`);
 const classRecords=Object.values(db.sessions).filter(s=>s.identity&&(!reportClass||s.identity.classroom===reportClass));const records=classRecords.filter(s=>reportSession==='all'||s.id===reportSession);
 function exportCsv(){const rows=[['時間','班級','座號','姓名','學習總分','形成性首次','遊戲最近','極限最高'],...records.map(s=>[s.updatedAt,s.identity.classroom,s.identity.seat,s.identity.name,learningTotal(s),s.assessment?.score,s.game?.score,s.challenge?.best])];const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8;'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='尺度探索站_本機學習紀錄.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 return <div className={`site page-${page}`}><a className="skip-link" href="#main">跳至主要內容</a><header className="site-header"><button className="logo-button" onClick={()=>navigate(0)} aria-label="尺度探索站首頁"><Logo/></button><nav aria-label="主要導覽"><button onClick={()=>setModal('map')}><MapIcon size={17}/><span>課程地圖</span></button><button onClick={()=>setModal('help')}><BookOpen size={17}/><span>學習說明</span></button></nav></header><div className="review-banner"><span><ShieldCheck size={15}/>{teacher?'教師預覽：全頁解鎖，練習不寫入學生紀錄':`逐頁解鎖 · 成績同步：${({idle:'尚未產生成績',syncing:'上傳中',synced:'已上傳',pending:'待網路恢復後重送'})[syncStatus]}`}</span><div>{teacher&&<button onClick={()=>setModal('report')}>本機學習紀錄</button>}<button onClick={()=>setModal('design')}>對照本頁草圖</button></div></div>{saveError&&<div className="storage-warning" role="alert">瀏覽器無法保存進度。目前仍可操作，請勿關閉頁面；檢查儲存空間或隱私設定。</div>}
 {page!==0&&<div className="progress-shell"><button className={`teacher-button ${teacher?'active':''}`} onClick={()=>teacher?(setTeacher(false),setToast('已回到學生模式，恢復原本學生進度')):setModal('teacher')}>{teacher?<LogOut size={16}/>:<Lock size={16}/>}<span>{teacher?'離開預覽':'教師模式'}</span></button><nav className="progress-nav" ref={navRef} aria-label="課程進度">{pages.slice(1).map(p=><button key={p.id} disabled={!canVisit(p.id)} onClick={()=>navigate(p.id)} aria-current={page===p.id?'page':undefined} className={`${done[p.id]?'done':''} ${page===p.id?'current':''}`}><span className="progress-icon">{!canVisit(p.id)?<Lock size={15}/>:done[p.id]?<Check size={15}/>:p.id===9?<Trophy size={15}/>:p.id===10?<FlagIcon/>:<span>{p.id}</span>}</span>{p.short}</button>)}</nav></div>}
 <main id="main" key={`${page}-${teacher?'teacher':'student'}`}>
 {page===0?<HomePage session={session} start={start} onIdentityEditing={clearForEditing} navigate={navigate} restart={()=>setModal('restart')} canVisit={canVisit}/>:<>
 {[2,3,4,5,7,8,9].includes(page)&&<DesignHero page={page}/>}
 {page===1&&<Intro navigate={navigate} completed={session.intro} response={session.introResponse} onComplete={response=>update(s=>({...s,intro:true,introResponse:response}))}/>}
 {page>=2&&page<=6&&<><Activities page={page}/><Practice page={page} session={session} onSubmit={submit}/></>}
 {page===7&&<Assessment result={session.assessment} navigate={navigate} onComplete={r=>update(s=>s.assessment?s:{...s,assessment:r})}/>}
 {page===7&&<ReviewTopics navigate={navigate}/>}
 {page===8&&<SortingGame saved={session.game} navigate={navigate} onComplete={r=>update(s=>({...s,game:{...r,best:Math.max(s.game?.best||0,r.score)}}))}/>}
 {page===9&&<Challenge canAdvance={canVisit(10)} saved={session.challenge} leaderboard={ranking.entries} leaderboardStatus={ranking.status} refreshLeaderboard={ranking.refresh} navigate={navigate} onComplete={r=>update(s=>({...s,challenge:{...r,maxAnswered:Math.max(s.challenge?.maxAnswered??s.challenge?.answered??0,r.answered),first:s.challenge?.first??r.score,best:Math.max(s.challenge?.best||0,r.score)}}))}/>}
 {page===10&&<Results session={session} navigate={navigate} done={done}/>}
 </>}
 {page!==0&&page!==10&&<footer className="page-navigation"><button className="secondary" onClick={()=>navigate(page-1)}><ArrowLeft size={17}/>上一頁</button><button className="home-link" onClick={()=>navigate(0)} aria-label="回到首頁"><Home size={22}/></button><div className="footer-progress"><span>學習完成 {percent}%</span><progress max="100" value={percent}/><small>{done[page]?'本頁指定活動已完成':teacher?'教師模式可自由切頁':'完成本頁所有題目與指定活動後，解鎖下一頁'}</small></div><button className="primary" disabled={!canVisit(page+1)} onClick={()=>navigate(page+1)}>前往{pages[page+1].short}<ArrowRight size={17}/></button></footer>}
 <Landscape/></main><footer className="site-footer"><Logo/><p>用科學的眼光，看見不一樣的世界。</p><span>觀察 · 思考 · 實踐 · 成長</span>{page===0&&<button className="text-button" onClick={()=>setModal('teacher')}><Lock size={14}/>教師模式</button>}</footer>{toast&&<div className="toast" role="status"><Check size={19}/>{toast}</div>}
 {modal==='restart'&&<Modal title="開始新的學習場次" onClose={()=>setModal(null)}><p>將以目前的班級、座號與姓名重新開始。新場次的進度及分數歸零，先前紀錄仍保留於本機教師檢查中。</p><div className="between"><button className="secondary" onClick={()=>setModal(null)}>保留目前進度</button><button className="primary" onClick={()=>{const s=newSession(session.identity);if(teacher)setTeacherSession(s);else setDb(prev=>({...prev,active:s.id,sessions:{...prev.sessions,[s.id]:s}}));navigate(1);}}>開始新場次<ArrowRight size={17}/></button></div></Modal>}
 {modal==='map'&&<Modal title="這趟旅程的地圖" onClose={()=>setModal(null)} wide><p>完成率 {percent}% · {teacher?'教師模式可自由查看全部頁面。':'完成本頁所有題目與指定活動後，解鎖下一頁。'}</p><div className="map-list">{pages.map(p=><button key={p.id} disabled={!canVisit(p.id)} onClick={()=>navigate(p.id)}><span>{String(p.id+1).padStart(2,'0')}</span><strong>{p.name}</strong>{!canVisit(p.id)?<Lock size={20}/>:done[p.id]?<Check size={20}/>:<ChevronRight size={18}/>}</button>)}</div></Modal>}
 {modal==='help'&&<Modal title="如何開始你的探索" onClose={()=>setModal(null)}><ol className="help-list"><li><strong>先讀、再操作。</strong>點關鍵字查看概念，動手改變變數、比對結果。</li><li><strong>練習可以修正。</strong>首次答對 3 分，第二次 2 分，第三次起 1 分。五個主題合計最高 75 分。</li><li><strong>評量一次提交。</strong>10 題全答完再送出，保留首次成績，提交後可回顧薄弱概念。</li><li><strong>四類成績分開。</strong>練習、形成性、遊戲與極限挑戰各自記錄。</li><li><strong>本機續學與成績上傳。</strong>重整保留進度；產生成績後會同步至教師成績表。離線時先保留，恢復網路後重送。</li></ol><p className="hint">學習進度仍保存在目前瀏覽器；成績摘要會上傳，網站沒有連接 Firebase。</p></Modal>}
 {modal==='design'&&<Modal title={`${pages[page].name}｜原始草圖`} onClose={()=>setModal(null)} wide><p className="hint">網頁依此草圖重建為可操作元件；構造圖與比例尺另以可驗證的圖形呈現。</p><img className="design-reference" src={`${import.meta.env.BASE_URL}designs/${designFiles[page]}`} alt={pages[page].name+'完整設計草圖'}/></Modal>}
 {modal==='teacher'&&<Modal title="教師預覽" onClose={()=>{setModal(null);setPasswordError('');}}><p>用來巡覽題目與解析，預覽作答不會寫入學生的學習紀錄。</p><form onSubmit={e=>{e.preventDefault();if(password==='55688'){setTeacher(true);setTeacherSession(newSession());setModal(null);setPassword('');setPasswordError('');}else setPasswordError('密碼不正確，請再試一次。');}}><label>預覽密碼<input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{passwordError&&<p role="alert" className="error-text">{passwordError}</p>}<button className="primary">進入教師預覽<ArrowRight size={17}/></button></form><p className="hint">此入口只提供本機教學檢查，不是正式帳號認證。</p></Modal>}
 {modal==='report'&&teacher&&<Modal title="本機學習紀錄" onClose={()=>setModal(null)} wide><div className="report-filters"><label>班級<select value={reportClass} onChange={e=>{setReportClass(e.target.value);setReportSession('all');}}><option value="">全部班級</option>{[...new Set(Object.values(db.sessions).map(s=>s.identity?.classroom).filter(Boolean))].map(c=><option key={c}>{c}</option>)}</select></label><label>學習場次<select value={reportSession} onChange={e=>setReportSession(e.target.value)}><option value="all">全部場次</option>{classRecords.map(s=><option key={s.id} value={s.id}>{s.identity.name}・{new Date(s.createdAt).toLocaleString('zh-TW')}</option>)}</select></label><label>題目主題<select value={reportTopic} onChange={e=>setReportTopic(e.target.value)}><option value="all">全部主題</option>{[2,3,4,5,6].map(p=><option key={p} value={p}>{pages[p].name}</option>)}</select></label><button className="secondary" onClick={exportCsv}><Download size={17}/>匯出本機紀錄</button></div><p className="hint">僅限這個瀏覽器曾使用的學習場次，並非全班雲端成績。同一學生不同場次分列。</p><div className="table-scroll"><table><thead><tr><th>班級／座號</th><th>姓名</th><th>場次</th><th>完成練習</th><th>練習分數</th><th>評量</th><th>遊戲</th><th>挑戰最高</th></tr></thead><tbody>{records.map(s=><tr key={s.id}><td>{s.identity.classroom} / {s.identity.seat}</td><td>{s.identity.name}</td><td>{new Date(s.createdAt).toLocaleString('zh-TW')}</td><td>{Object.keys(s.solved).length} / 25</td><td>{learningTotal(s)} / 75</td><td>{s.assessment?.score??'—'}</td><td>{s.game?.score??'—'}</td><td>{s.challenge?.best??'—'}</td></tr>)}</tbody></table></div><h3>題目作答次數、答對率與常見錯答</h3><p className="hint">答對率以所有提交次數計算，包含重試。</p><div className="teacher-answer-list">{Object.entries(questions).filter(([p])=>reportTopic==='all'||reportTopic===p).flatMap(([,qs])=>qs).map(q=>{const ev=records.flatMap(s=>s.events).filter(e=>e.question===q.id);const wrong=ev.filter(e=>!e.correct);const freq={};wrong.forEach(e=>{const v=Array.isArray(e.answer)?e.answer.join('／'):e.answer;freq[v]=(freq[v]||0)+1;});const common=Object.entries(freq).sort((a,b)=>b[1]-a[1])[0];return <details key={q.id}><summary>{q.title} · {ev.length?Math.round(ev.filter(e=>e.correct).length/ev.length*100)+'%':'尚無作答'}（{ev.length} 次）</summary><p>正解：{Array.isArray(q.answer)?q.answer.join(' → '):q.answer}</p><p>{q.explain}</p><p>常見錯答：{common?`${common[0]}（${common[1]} 次）`:'—'}</p></details>;})}</div><details><summary>形成性評量答案與解析（教師檢查）</summary>{assessment.map((q,i)=><p key={q.id}>{i+1}. {q.prompt}<br/><strong>{q.answer}</strong>｜{q.explain}</p>)}</details></Modal>}
 </div>;
}
function FlagIcon(){return <Leaf size={15}/>;}
