import React,{useState,useEffect,useRef,useMemo} from 'react';
import {ArrowRight,ArrowLeft,Check,Lock,Heart,Trophy,RotateCcw,Clock,Play,Pause,Lightbulb,Gamepad2,Flag} from 'lucide-react';
import {assessment,gameCards,challengeBank,pages} from './data';
import {shuffle,gradeAssessment,challengePoints} from './engine';
import {QuestionInput} from './Questions';
import {ScaleArt,Motif,Photo} from './Art';
import {SpecimenVisual} from './DesignSystem';
const assessmentScenes={
 a1:{page:6,region:[45,602,268,107],label:'蓮葉上的水滴'},
 a2:{page:2,region:[404,389,694,193],label:'同一片麵包在不同觀察尺度下的外觀'},
 a3:{type:'cell'},
 a4:{page:3,region:[43,418,1099,129],label:'從微小物體到巨大天體的尺度'},
 a5:{page:4,region:[626,150,482,221],label:'蜂鳥照片示意，不能直接推算實際體長'},
 a7:{page:5,region:[645,252,430,332],label:'池水中的生物觀察示意'},
 a8:{type:'paramecium'},
 a9:{page:6,region:[360,879,200,120],label:'魔鬼氈的鉤面與毛面'},
 a10:{page:6,region:[715,602,248,109],label:'雨水在防水表面的現象'}
};
function AssessmentVisual({id}){const scene=assessmentScenes[id];return scene.type?<SpecimenVisual type={scene.type}/>:<Photo {...scene}/>;}
export function Assessment({result,onComplete,navigate}){const [index,setIndex]=useState(0),[answers,setAnswers]=useState({}),[confirm,setConfirm]=useState(false);const q=assessment[index],count=Object.keys(answers).length;
 if(result)return <section className="panel assessment-result"><span className="eyebrow">首次提交已記錄</span><h2>把這次判斷，變成下一步的線索。</h2><div className="result-number">{result.score}<small>/ 10</small></div><p>10 題已全部完成。這個成績與學習練習分開記錄。</p>{result.weakPages.length?<><h3>可以再回顧的概念</h3><div className="review-links">{result.weakPages.map(p=><button className="secondary" key={p} onClick={()=>navigate(p)}>{pages[p].name}<ArrowRight size={16}/></button>)}</div><p className="hint">回到探索頁找證據，再用自己的話解釋原理。</p></>:<p className="feedback correct">你已掌握這次評量中的核心概念。試著把方法應用在遊戲的新情境中。</p>}<button className="primary" onClick={()=>navigate(8)}>進入尺度快判<ArrowRight size={18}/></button></section>;
 return <section className="assessment-layout"><aside className="panel question-map"><h3>作答進度</h3><p>已作答 <strong>{count} / 10</strong> 題</p><div className="number-grid">{assessment.map((q,i)=><button aria-label={`評量第 ${i+1} 題${answers[q.id]?'，已作答':''}`} aria-current={index===i?'step':undefined} className={`${index===i?'current':''} ${answers[q.id]?'answered':''}`} key={q.id} onClick={()=>setIndex(i)}>{i+1}</button>)}</div><div className="map-legend"><span>● 已作答</span><span>◯ 目前題目</span><span>○ 未作答</span></div></aside><article className="panel exam-question"><span className="eyebrow">第 {index+1} 題｜{q.title}</span><h2>{q.prompt}</h2>{q.art?<ScaleArt ratio={4} bar={25} measure/>:<figure className="exam-context"><AssessmentVisual id={q.id}/><figcaption>觀察圖片提供的線索，再根據題目判斷。</figcaption></figure>}<QuestionInput key={q.id} q={q} value={answers[q.id]} onChange={v=>{setAnswers({...answers,[q.id]:v});setConfirm(false);}}/><p className="hint">提交前可以修改；本頁不逐題判分。</p><div className="between"><button className="secondary" disabled={index===0} onClick={()=>setIndex(index-1)}><ArrowLeft size={16}/>上一題</button><button className="primary" disabled={index===9} onClick={()=>setIndex(index+1)}>下一題<ArrowRight size={16}/></button></div></article><aside className="panel submit-panel"><h3>完成，再提交</h3><ol><li>作答全部題目</li><li>檢查未答題目</li><li>一次提交答案</li></ol><p>首次提交結果會保留。重新整理時，尚未提交的選項會清除。</p>{confirm?<div className="confirm-submit" role="alert"><p>10 題都已作答。確定提交並記錄首次成績？</p><button className="primary" onClick={()=>onComplete(gradeAssessment(assessment,answers))}>確定提交</button><button className="text-button" onClick={()=>setConfirm(false)}>再檢查一下</button></div>:<button className="primary" disabled={count<10} onClick={()=>setConfirm(true)}>{count<10?<Lock size={17}/>:<Check size={17}/>}提交評量</button>}<small>{count<10?`還有 ${10-count} 題未作答`:'全部作答完成，可提交'}</small></aside></section>;
}
export function SortingGame({saved,onComplete,navigate}){const [deck,setDeck]=useState(()=>shuffle(gameCards)),[started,setStarted]=useState(false),[index,setIndex]=useState(0),[score,setScore]=useState(0),[streak,setStreak]=useState(0),[feedback,setFeedback]=useState(null),[finished,setFinished]=useState(false);const latch=useRef(false);const card=deck[index];const options=useMemo(()=>shuffle(card.options),[card]);
 function answer(v){if(latch.current||!started||finished)return;latch.current=true;const correct=v===card.answer;setFeedback({correct,choice:v});setScore(s=>s+(correct?30:0));setStreak(s=>correct?s+1:0);}
 function next(){if(index===deck.length-1){setFinished(true);onComplete({score,total:deck.length*30,at:new Date().toISOString()});}else{setIndex(index+1);setFeedback(null);latch.current=false;}}
 function start(){setDeck(shuffle(gameCards));setIndex(0);setScore(0);setStreak(0);setFeedback(null);setFinished(false);setStarted(true);latch.current=false;}
 if(!started||finished)return <section className="panel game-start"><Photo page={8} region={[178,474,800,237]} label="草圖中的四個尺度分類槽"/><div><span className="eyebrow">單位快分／工具配對／比例尺挑戰</span><h2>{finished?'這一輪，你收集了新的判斷方法。':'把觀察線索，放進正確的位置。'}</h2>{finished?<div className="result-number">{score}<small>/ 270</small></div>:<p>共 9 張任務卡，答對一題得 30 分，答錯不扣分。每題都會給你解析，再進入下一張。</p>}{saved&&<p>最近一局 {saved.score} 分 · 本機最佳 {saved.best??saved.score} 分</p>}<button className="primary" onClick={start}>{finished?<RotateCcw size={18}/>:<Play size={18}/>} {finished?'再玩一次':'開始分類'}</button>{finished&&<button className="secondary" onClick={()=>navigate(9)}>前往極限挑戰<ArrowRight size={17}/></button>}</div></section>;
 return <section className="sorting-station"><div className="game-hud"><span><Gamepad2 size={18}/>{card.mode}</span><span>第 {index+1} / {deck.length} 回合</span><span>連續答對 {streak} 題</span><strong>本局得分 {score}</strong></div><div className="specimen-ticket" draggable={!feedback} onDragStart={e=>e.dataTransfer.setData('text/plain','specimen-card')}><Motif type={card.art}/><div><span className="eyebrow">觀察線索</span><h2>{card.name}</h2><p>{card.clue}</p></div></div><p className="center hint">拖曳卡片到分類槽，或直接點選分類槽。</p><div className="sorting-bins">{options.map((o,i)=><button key={o} disabled={!!feedback} className={feedback?.choice===o?(feedback.correct?'correct':'incorrect'):''} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(e.dataTransfer.getData('text/plain')==='specimen-card')answer(o);}} onClick={()=>answer(o)}><span className="bin-letter">{String.fromCharCode(65+i)}</span><strong>{o}</strong><span className="bin-slot"/></button>)}</div>{feedback&&<div className={`feedback game-feedback ${feedback.correct?'correct':'incorrect'}`} role="status"><div><strong>{feedback.correct?'分類成功！＋30 分':'先記住這個判斷方法。'}</strong><p>{card.explain}</p></div><button className="primary" onClick={next}>{index===deck.length-1?'查看本局成果':'下一張卡片'}<ArrowRight size={17}/></button></div>}<div className="notebook-callout"><Lightbulb/><p>先看「要觀察什麼」，再選工具與單位。圖像大小本身無法代表真實尺度。</p></div></section>;
}
export function Challenge({saved,onComplete,leaderboard,navigate}){const [deck,setDeck]=useState(()=>shuffle(challengeBank)),[started,setStarted]=useState(false),[finished,setFinished]=useState(false),[index,setIndex]=useState(0),[score,setScore]=useState(0),[lives,setLives]=useState(3),[position,setPosition]=useState(0),[feedback,setFeedback]=useState(null),[paused,setPaused]=useState(false);const latch=useRef(false),elapsed=useRef(0),last=useRef(0);const q=deck[index];const opts=useMemo(()=>shuffle(q.options),[q]);const duration=Math.max(14000,22000-index*350);
 function start(){setDeck(shuffle(challengeBank));setStarted(true);setFinished(false);setIndex(0);setScore(0);setLives(3);setPosition(0);setFeedback(null);setPaused(false);latch.current=false;elapsed.current=0;last.current=performance.now();requestAnimationFrame(()=>document.querySelector('.challenge-arena')?.scrollIntoView({block:'start',behavior:'instant'}));}
 function answer(choice,timeout=false){if(latch.current||!started||finished||paused)return;latch.current=true;const correct=!timeout&&choice===q.answer;const delta=correct?challengePoints(Math.min(100,elapsed.current/duration*100)):-1000;const nextScore=Math.max(0,score+delta),nextLives=lives-(correct?0:1);setScore(nextScore);setLives(nextLives);setFeedback({correct,delta,timeout,explain:q.explain});if(nextLives===0||index===deck.length-1){setFinished(true);onComplete({score:nextScore,at:new Date().toISOString(),answered:index+1});}else{setIndex(i=>i+1);setPosition(0);elapsed.current=0;last.current=performance.now();}}
 useEffect(()=>{latch.current=false;},[index]);
 useEffect(()=>{if(!started||finished||paused)return;last.current=performance.now();const timer=setInterval(()=>{const now=performance.now();elapsed.current+=now-last.current;last.current=now;const p=Math.min(100,elapsed.current/duration*100);setPosition(p);if(p>=100)answer(null,true);},40);return()=>clearInterval(timer);},[started,finished,index,paused]);
 useEffect(()=>{const hide=()=>{if(document.hidden&&started&&!finished)setPaused(true);};document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide);},[started,finished]);
 return <><section className="challenge-arena"><div className="game-hud"><strong>本局分數 <b>{score.toLocaleString()}</b></strong><span aria-label={`剩餘 ${lives} 次生命`}>{[1,2,3].map(n=><Heart key={n} className={n<=lives?'heart-filled':'heart-empty'} size={25}/>)}</span><span>{started&&!finished?`${index+1} / ${deck.length}`:'速度與正確率'}</span></div>{!started||finished?<><div className="challenge-welcome"><div className="challenge-photo"><Photo page={9} region={[213,362,377,207]} label="植物細胞構造示意" fit="slice"/><span>植物細胞・構造示意</span></div><div><h2>{finished?'每次判斷，都是新的累積。':'準備挑戰你的反應極限。'}</h2><p>讀懂題目，選出答案。愈快答對，得分愈高；答錯或逾時扣 1,000 分並失去 1 次生命。共 {deck.length} 題，3 次失誤結束。</p><p>每題約 16–22 秒。作答或逾時後立即換題；切換視窗會自動暫停。</p><button className="primary" onClick={start}>{finished?'再挑戰一次':'準備好了，開始'}<Play size={18}/></button>{finished&&<button className="secondary" onClick={()=>navigate(10)}>查看學習成果<ArrowRight size={18}/></button>}</div></div>{finished&&<div className="challenge-finish"><Trophy size={58}/><h2>本局完成！</h2><div className="challenge-score">{score.toLocaleString()}<span>本次得分</span></div></div>}</>:<><div className="speed-track" role="progressbar" aria-label="本題經過時間" aria-valuenow={Math.round(position)} aria-valuemin={0} aria-valuemax={100}><span style={{width:`${position}%`}}/></div><div className="between timer-line"><span><Clock size={15}/>剩餘 {Math.max(0,Math.ceil(duration*(1-position/100)/1000))} 秒</span><button  className="text-button" onClick={()=>setPaused(!paused)}>{paused?<Play size={16}/>:<Pause size={16}/>} {paused?'繼續':'暫停'}</button></div>{paused?<div className="pause-panel"><Pause size={44}/><h2>挑戰已暫停</h2><p>準備好再繼續，本題經過的時間會保留。</p><button className="primary" onClick={()=>setPaused(false)}>繼續挑戰</button></div>:<><div className="challenge-round"><div className="challenge-photo">{q.art&&q.art!=='assessment-scale'?<SpecimenVisual type={q.art}/>:<Photo page={9} region={[212,363,377,237]} label="細胞構造示意" fit="slice"/>}<span>{q.art&&q.art!=='assessment-scale'?'觀察情境示意・非等比圖':'植物細胞・構造示意'}</span></div><div className="round-content"><div className="challenge-question"><span className="eyebrow">{q.title||q.name}</span><h2>{q.prompt}</h2>{q.art==='assessment-scale'?<ScaleArt ratio={4} bar={25}/>:null}</div><div className="options">{opts.map(o=><button  key={o} onClick={()=>answer(o)}>{o}</button>)}</div></div></div>{feedback&&<div className={`feedback ${feedback.correct?'correct':'incorrect'}`} role="status"><strong>{feedback.timeout?'上一題時間到。':feedback.correct?`上一題答對！＋${feedback.delta.toLocaleString()} 分`:'上一題答錯。－1,000 分'}</strong><p>{feedback.explain}</p></div>}</>}</>}
 <div className="challenge-rules"><span>答對 500–5,000 分</span><span>答錯扣 1,000 分</span><span>分數最低為 0</span></div></section><section className="panel leaderboard"><div className="section-heading"><div><span className="eyebrow">每人保留最高分</span><h2>挑戰排行榜</h2></div><span className="badge">本機紀錄・匿名代碼</span></div><p className="hint">目前只顯示這個瀏覽器的紀錄。全班排行榜將在正式資料連接後提供。</p>{leaderboard.length?<div className="ranking-columns">{[0,5].filter(start=>leaderboard.length>start).map(start=><div key={start}><table><thead><tr><th>排名</th><th>匿名代號</th><th>最高分</th></tr></thead><tbody>{leaderboard.slice(start,start+5).map((r,i)=><tr key={r.key}><td><span className={`rank rank-${start+i}`}>{start+i+1}</span></td><td>{r.alias}</td><td>{r.score.toLocaleString()}</td></tr>)}</tbody></table></div>)}</div>:<div className="empty-state"><Flag/><p>還沒有已完成的挑戰。完成一局，留下第一個紀錄。</p></div>}{saved&&<p>你的首次成績：{saved.first.toLocaleString()} · 個人最高：{saved.best.toLocaleString()}</p>}</section></>;
}
