import React,{useState,useMemo} from 'react';
import {Check,RotateCcw,ArrowUp,ArrowDown,Target,Lightbulb,ChevronRight} from 'lucide-react';
import {shuffle,isComplete,checkAnswer,learningTotal} from './engine';
import {questions} from './data';
import {Cell,Motif,ScaleArt,Photo} from './Art';
import {SpecimenVisual,ToolVisual} from './DesignSystem';
export const typeNames={single:'單選',blanks:'下拉填空',classify:'快速分類',hotspot:'圖片標示',multi:'證據複選',match:'配對',order:'因果排序',number:'數值填充',boolean:'是非判斷',diagnosis:'情境診斷',direction:'方向操作',cer:'主張・證據・推理'};
function SimpleScaleQuestion(){return <svg className="simple-scale-question" viewBox="0 0 480 180" role="img" aria-label="物體分成三個等長部分，每一部分與代表 10 mm 的比例尺一樣長" style={{width:'100%',maxWidth:600,display:'block',margin:'16px auto',background:'#edf5ef',borderRadius:12}}><text x="45" y="60" fill="#173342" textAnchor="middle" fontSize="16">物體</text><rect x="90" y="32" width="300" height="48" rx="4" fill="#74b5a5" stroke="#087f82" strokeWidth="2"/><path d="M190 32V80M290 32V80" stroke="#fff" strokeWidth="2" strokeDasharray="5 4"/><path d="M90 112V128M90 120H190M190 112V128" stroke="#173342" strokeWidth="3"/><text x="140" y="151" textAnchor="middle" fontSize="18" fill="#173342">10 mm</text><text x="285" y="128" textAnchor="middle" fontSize="14" fill="#173342">3 個一樣長的部分</text></svg>;}
export function QuestionInput({q,value,onChange,disabled=false,seed=0}){
 const options=useMemo(()=>q.type==='hotspot'||q.type==='direction'?q.options:shuffle(q.options||[]),[q,seed]);
 const choices=useMemo(()=>q.choices?.map(shuffle),[q,seed]);
 const setRow=(i,v)=>{const a=Array.from({length:q.answer.length},(_,j)=>value?.[j]||'');a[i]=v;onChange(a);};
 if(q.type==='number')return <label className="number-input"><input aria-label="填入答案" type="text" inputMode="decimal" placeholder="輸入數字" value={value??''} disabled={disabled} onChange={e=>onChange(e.target.value)}/><span>{q.unit}</span></label>;
 if(q.type==='order'){const selected=value||[];return <div className="ordering"><p className="hint">依順序點選下方步驟；可用上下鍵調整，或移除後重選。</p><ol>{selected.map((s,i)=><li key={s}><span>{s}</span><div><button type="button" aria-label={`將「${s}」上移`} disabled={disabled||i===0} onClick={()=>{const a=[...selected];[a[i-1],a[i]]=[a[i],a[i-1]];onChange(a);}}><ArrowUp size={16}/></button><button type="button" aria-label={`將「${s}」下移`} disabled={disabled||i===selected.length-1} onClick={()=>{const a=[...selected];[a[i+1],a[i]]=[a[i],a[i+1]];onChange(a);}}><ArrowDown size={16}/></button><button type="button" disabled={disabled} aria-label={`移除「${s}」`} onClick={()=>onChange(selected.filter(x=>x!==s))}>×</button></div></li>)}</ol><div className="step-pool">{q.initial.filter(s=>!selected.includes(s)).map(s=><button type="button" disabled={disabled} key={s} onClick={()=>onChange([...selected,s])}>{s} <ChevronRight size={15}/></button>)}</div></div>;}
 if(['match','blanks','classify','diagnosis','cer'].includes(q.type))return <div className={`answer-rows ${q.type==='cer'?'cer-rows':''} ${q.id==='u1'?'match-illustrated':''}`}>{q.rows.map((row,i)=><label key={row}>{q.id==='u1'&&<SpecimenVisual type={['euglena','person','mountain','galaxy'][i]}/>}<span><b>{String(i+1).padStart(2,'0')}</b>{row}</span><select aria-label={row} disabled={disabled} value={value?.[i]||''} onChange={e=>setRow(i,e.target.value)}><option value="">選擇答案</option>{(choices?.[i]||options).map(o=><option key={o} value={o}>{o}</option>)}</select></label>)}</div>;
 if(q.type==='hotspot')return <div className="hotspot-task"><div className="hotspot-picture">{q.art==='euglena'?<Cell type="euglena"/>:q.art==='burr'?<Motif type="burr"/>:<div className="photo-trio"><Photo page={2} region={[432,403,160,160]} label="整體麵包"/><Photo page={2} region={[614,390,173,171]} label="黴斑"/><Photo page={2} region={[834,392,193,188]} label="菌絲細部"/></div>}{options.map(([id,label],i)=>{const coordinates=q.art==='euglena'?[[55,63],[60,28],[77,12]]:q.art==='burr'?[[75,61],[80,25],[45,54]]:[[16,52],[50,52],[84,52]];return <button type="button" className={'image-marker '+(value===id?'selected':'')} aria-label={'圖中標記 '+(i+1)} aria-pressed={value===id} disabled={disabled} key={id} style={{left:coordinates[i][0]+'%',top:coordinates[i][1]+'%'}} onClick={()=>onChange(id)}>{i+1}</button>;})}</div><div className="hotspot-options">{options.map(([id,label],i)=><button type="button" aria-pressed={value===id} className={value===id?'selected':''} disabled={disabled} key={id} onClick={()=>onChange(id)}><span className="target-marker">{i+1}</span>{label}</button>)}</div></div>;
 if(q.type==='direction')return <div className="direction-question"><div className="mini-field"><Cell type="euglena"/><span>影像往右下離開 ↘</span></div><div className="direction-grid">{['左上','上','右上','左','中央','右','左下','下','右下'].map((d,i)=>d==='中央'?<span key={d}>玻片</span>:<button type="button" aria-label={`玻片往${d}`} aria-pressed={value===d} disabled={disabled} className={value===d?'selected':''} key={d} onClick={()=>onChange(d)}>{['↖','↑','↗','←','','→','↙','↓','↘'][i]}<small>{d}</small></button>)}</div></div>;
 return <div className={`options ${q.type==='boolean'?'boolean':''} ${q.id==='o1'?'illustrated-tools':''}`}>{options.map((o,i)=>{const chosen=q.type==='multi'?(value||[]).includes(o):value===o;return <button type="button" key={o} aria-pressed={chosen} disabled={disabled} className={chosen?'selected':''} onClick={()=>onChange(q.type==='multi'?(chosen?value.filter(x=>x!==o):[...(value||[]),o]):o)}><span className={q.type==='multi'?'checkbox':'option-letter'}>{chosen?<Check size={18}/>:String.fromCharCode(65+i)}</span>{q.id==='o1'&&<ToolVisual name={o}/>}<span>{o}</span></button>;})}</div>;
}
function PracticeQuestion({q,session,onSubmit}){
 const solved=session.solved[q.id];const [value,setValue]=useState(solved?.answer);const [feedback,setFeedback]=useState(null);const [seed,setSeed]=useState(0);
 const locked=!!solved||!!feedback;
 function submit(){if(!isComplete(q,value)||locked)return;const correct=checkAnswer(q,value);onSubmit(q,value);setFeedback({correct});}
 return <article className={`practice-question ${solved?'correct':feedback?'incorrect':''}`} data-question={q.id}><div className="question-heading"><span className="eyebrow">{typeNames[q.type]}</span>{solved&&<span className="completed"><Check size={16}/>已完成 · {solved.points} 分</span>}</div><h3>{q.title}</h3><p className="prompt">{q.prompt}</p>{q.required&&<p className="hint">請選 {q.required} 項。目前已選 {value?.length||0} 項。</p>}{q.art==='scale'&&<ScaleArt measure/>}{q.art==='scale-basic'&&<SimpleScaleQuestion/>}{q.art==='orchid'&&<div className="reference-ratio"><span className="coin">1 元<br/>圖上 2 cm</span><span>花朵圖長 3 cm<br/>實際硬幣 2 cm</span><strong>3 ÷ 2 ＝ ？倍</strong></div>}
 <QuestionInput q={q} value={value} onChange={setValue} disabled={locked} seed={seed}/>
 {(solved||feedback)&&<div className={`feedback ${solved?'correct':'incorrect'}`} role="status"><strong>{solved?'觀察與推理都到位了。':'再檢查一下你的推理。'}</strong><p>{q.explain}</p>{!solved&&<button className="secondary" onClick={()=>{setValue(undefined);setFeedback(null);setSeed(x=>x+1);}}><RotateCcw size={16}/>重新作答</button>}</div>}
 {!locked&&<div className="question-actions"><span className="hint">第 {(session.attempts[q.id]||0)+1} 次作答 · 答對可得 {Math.max(1,3-(session.attempts[q.id]||0))} 分</span><button className="primary" disabled={!isComplete(q,value)} onClick={submit}>檢查答案 <Check size={17}/></button></div>}
 </article>;
}
export function Practice({page,session,onSubmit}){const qs=questions[page];const [index,setIndex]=useState(0);const count=qs.filter(q=>session.solved[q.id]).length;return <section className="practice-section" id="practice"><div className="section-heading"><div><span className="eyebrow"><Target size={16}/>把觀察用在新情境</span><h2>{({2:'把觀察用在新情境',3:'選一個合理的單位',4:'把比例變成判斷',5:'任務練習',6:'為你的設計找證據'})[page]}</h2></div><div className="progress-count">已完成 <strong>{count}</strong> / {qs.length}<small>學習總分 {learningTotal(session)} / 75</small></div></div><div className="question-tabs" role="tablist" aria-label="練習題目">{qs.map((q,i)=><button role="tab" aria-selected={index===i} key={q.id} className={index===i?'active':''} onClick={()=>setIndex(i)}>{session.solved[q.id]?<Check size={17}/>:<span>{i+1}</span>}{typeNames[q.type]}</button>)}</div><PracticeQuestion key={`${qs[index].id}-${session.id}`} q={qs[index]} session={session} onSubmit={onSubmit}/><div className="practice-bottom"><span><Lightbulb size={17}/>答錯後讀解析，再重新作答；完成以答對為準。</span><button className="text-button" disabled={index===4} onClick={()=>setIndex(index+1)}>下一個練習 <ChevronRight size={17}/></button></div></section>;}
