import React from 'react';
import {BookOpen,Check,Gamepad2,Trophy,ArrowRight,Home,RotateCcw} from 'lucide-react';
import {questions,pages} from './data';
import {learningTotal} from './engine';
import {Photo} from './Art';
import {HeroArt,TopicTrail,MethodStrip} from './DesignSystem';
export function Results({session,navigate,done}){const total=learningTotal(session);const weak=[...new Set([...(session.assessment?.weakPages||[]),...[2,3,4,5,6].filter(p=>questions[p].some(q=>!session.solved[q.id]||(session.solved[q.id]?.attempt||0)>1))])];return <>
 <section className="results-hero"><HeroArt page={10}/>{!done.slice(1,10).every(Boolean)&&<div className="journey-status-stamp">探索進行中<small>持續觀察，繼續發現</small></div>}<div className="results-copy"><span className="eyebrow">我的學習成果</span><h1>{done.slice(1,10).every(Boolean)?'你已經學會，':'每一次探索，'}<br/>用尺度看世界。</h1><p>從一片葉子、一滴池水，到微小的生命與偉大的設計，<br/>你用觀察與思考，累積自己的理解。</p><p className="hand-note">小小的探索，<br/>能帶來大大的改變。</p><span className="badge">學習者：{session.identity?.name||'探索者'} · {done.slice(1,10).filter(Boolean).length} / 9 項活動完成</span></div></section>
 <section className="score-cards">{[['學習表現',total,'/ 75','25 題練習的作答表現',BookOpen,[28,483,267,94]],['形成性評量',session.assessment?.score??'—','/ 10','首次提交結果',Check,[320,483,257,94]],['學習遊戲',session.game?.score??'—','','最近一局積分',Gamepad2,[600,483,267,94]],['極限挑戰',session.challenge?.best?.toLocaleString()??'—','','個人最高分',Trophy,[888,483,266,94]]].map(([name,score,denom,sub,Icon,r])=><div key={name}><Photo page={10} region={r} label={name}/><div className="score-content"><span className="score-icon"><Icon size={28}/></span><div><h3>{name}</h3><strong>{score}<small>{denom}</small></strong><p>{sub}</p></div></div></div>)}</section>
 <div className="results-review-grid"><section className="panel results-footprints"><h2>我的探索足跡</h2><p>5 個主題的指定練習，留下理解的證據。</p><TopicTrail navigate={navigate} compact done={done} questions={questions} session={session}/></section><section className="panel results-reflection"><h2>把理解再推進一步</h2><p>再看一次比例尺推理，<br/>說清楚你如何從圖片估計真實大小。</p><Photo page={10} region={[811,820,192,88]} label="草履蟲與比例尺示意"/><button className="primary" onClick={()=>navigate(4)}>重看比例尺<ArrowRight size={18}/></button>{weak.filter(p=>p!==4).length>0&&<details><summary>其他可回顧的概念</summary><div className="review-links">{weak.filter(p=>p!==4).map(p=><button key={p} className="text-button" onClick={()=>navigate(p)}>{pages[p].short}<ArrowRight size={14}/></button>)}</div></details>}</section></div>
 <MethodStrip/><div className="results-actions"><button className="secondary" onClick={()=>navigate(9)}>← 上一頁</button><button className="primary" onClick={()=>navigate(0)}><Home size={20}/>回到首頁</button><button className="secondary" onClick={()=>navigate(9)}><RotateCcw size={17}/>重新挑戰</button><button className="secondary" onClick={()=>navigate(2)}><BookOpen size={17}/>回顧學習內容</button></div></>;}
