import React,{useState,useMemo,useRef} from 'react';
import {ArrowRight,Gamepad2,Play,RotateCcw,Check,Lightbulb} from 'lucide-react';
import {gameCards} from './data';
import {shuffle} from './engine';
import {Photo} from './Art';
import {SpecimenVisual,ToolVisual} from './DesignSystem';
const modes=['單位快分','工具配對','比例尺挑戰'];
function binType(s){if(s.includes('微米'))return 'cell';if(s.includes('毫米'))return 'seed';if(s.includes('奈米'))return 'atom';if(s.includes('公里'))return 'mountain';if(s.includes('公尺'))return 'person';if(s.includes('光年'))return 'galaxy';return null;}
const descriptions={'公尺':'適合描述較大的物體，如人體、樹木與建築。','毫米':'適合描述小型物體，如芝麻與昆蟲身體。','微米':'適合描述細胞及許多微小生物。','奈米':'適合描述原子、分子等極微小結構。','公里':'常用於城市間路程與大型地形。','光年':'用來描述極大的天文距離。'};
export function SortingGame({saved,onComplete,navigate}){
 const [mode,setMode]=useState(modes[0]),[deck,setDeck]=useState(()=>shuffle(gameCards)),[started,setStarted]=useState(false),[index,setIndex]=useState(0),[score,setScore]=useState(0),[streak,setStreak]=useState(0),[feedback,setFeedback]=useState(null),[finished,setFinished]=useState(false);const latch=useRef(false);
 const preview=gameCards.find(c=>c.mode===mode)||gameCards[0],card=started?deck[index]:preview;
 const options=useMemo(()=>shuffle(card.options),[card]);
 function answer(v){if(latch.current||!started||finished)return;latch.current=true;const correct=v===card.answer;setFeedback({correct,choice:v});setScore(s=>s+(correct?30:0));setStreak(s=>correct?s+1:0);}
 function next(){if(index===deck.length-1){setFinished(true);onComplete({score,total:deck.length*30,at:new Date().toISOString()});}else{setIndex(index+1);setFeedback(null);latch.current=false;}}
 function start(){setDeck([...shuffle(gameCards.filter(c=>c.mode===mode)),...shuffle(gameCards.filter(c=>c.mode!==mode))]);setIndex(0);setScore(0);setStreak(0);setFeedback(null);setFinished(false);setStarted(true);latch.current=false;}
 return <><section className="sorting-station"><div className="lab-decor" aria-hidden="true"><Photo page={8} region={[0,328,155,270]} label=""/><Photo page={8} region={[1051,151,131,445]} label=""/></div><div className="game-hud"><span><Gamepad2 size={18}/>{started?card.mode:mode}</span><span>{started?`第 ${index+1} / ${deck.length} 回合`:'準備探索'}</span><span>連續答對 {streak} 題</span><strong>本局得分 {score}</strong></div>
 {finished?<div className="game-finished"><h2>這一輪，你收集了新的判斷方法。</h2><div className="result-number">{score}<small>/ 270</small></div><p>完成 9 張任務卡。每一次判斷，都要回到觀察目的與證據。</p><button className="primary" onClick={start}><RotateCcw size={18}/>再玩一次</button><button className="secondary" onClick={()=>navigate(9)}>前往極限挑戰<ArrowRight size={18}/></button></div>:<><div className="specimen-ticket" draggable={started&&!feedback} onDragStart={e=>e.dataTransfer.setData('text/plain','specimen-card')}><SpecimenVisual type={card.art}/><div><span className="eyebrow">觀察線索</span><h2>{card.name}</h2><p>{card.clue}</p></div></div><p className="center hint">拖曳卡片，或點選下方分類槽。</p><div className="sorting-bins">{options.map((o,i)=>{const t=binType(o),d=Object.entries(descriptions).find(([k])=>o.includes(k))?.[1];return <button key={o} disabled={!started||!!feedback} className={feedback?.choice===o?(feedback.correct?'correct':'incorrect'):''} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(e.dataTransfer.getData('text/plain')==='specimen-card')answer(o);}} onClick={()=>answer(o)}><span className="bin-letter">{String.fromCharCode(65+i)}</span><strong>{o}</strong>{t?<SpecimenVisual type={t}/>:card.mode==='工具配對'?<div className="bin-tool"><ToolVisual name={o}/></div>:<div className="bin-measure"><span>↔</span><i/><small>用比例與證據判斷</small></div>}<span className="bin-slot"/>{d&&<small>{d}</small>}</button>;})}</div>
 {!started&&<div className="game-start-controls"><p>共 9 張任務卡。答對一題得 30 分，答錯不扣分。每題先讀解析，再進入下一張。下方可選擇先從哪一類任務開始。</p><button className="primary" onClick={start}><Play size={18}/>開始分類</button></div>}
 {feedback&&<div className={`feedback game-feedback ${feedback.correct?'correct':'incorrect'}`} role="status"><Check size={34}/><div><strong>{feedback.correct?'分類成功！＋30 分':'先記住這個判斷方法。'}</strong><p>{card.explain}</p></div><button className="primary" onClick={next}>{index===deck.length-1?'查看本局成果':'下一張卡片'}<ArrowRight size={17}/></button></div>}</>}
 {saved&&<p className="hint center">最近一局 {saved.score} 分 · 本機最佳 {saved.best??saved.score} 分</p>}</section>
 <div className="game-mode-tabs">{modes.map(m=><button key={m} aria-pressed={mode===m} className={mode===m?'active':''} onClick={()=>setMode(m)}>{m}</button>)}</div><section className="game-notebook"><h2>{started?'這回合學到什麼？':'先把判斷方法準備好。'}</h2><div>{mode==='單位快分'?<><article><SpecimenVisual type="cell"/><h3>小尺度不等於小數字</h3><p>1 微米（μm）＝ 0.001 毫米（mm）。同一個長度，換成較小的單位，數值會變大。</p></article><article><SpecimenVisual type="seed"/><h3>選擇適當單位</h3><p>同一個物體可以用不同單位表示；選擇能清楚表達大小、方便比較的單位。</p></article></>:mode==='工具配對'?<><article><SpecimenVisual type="bread"/><h3>先問觀察目的</h3><p>描述整片麵包的黴斑分布，需要保留整體視野。提高倍率不一定比較有用。</p></article><article><SpecimenVisual type="paramecium"/><h3>看見，不等於看清</h3><p>要分辨纖毛等微小構造，需要足夠的放大與解析能力，並適當製備樣本。</p></article></>:<><article><SpecimenVisual type="paramecium"/><h3>先找線段代表的長度</h3><p>真實長度＝圖上物體與線段的長度比 × 比例尺標示。注意單位。</p></article><article><SpecimenVisual type="snail"/><h3>也可以反過來推理</h3><p>知道物體真實體長及圖上比值，就能推算比例尺線段應標示多少。</p></article></>}</div>{started&&!finished&&<p className="hint">切換下方說明不會更改進行中的 9 回合或成績。</p>}</section></>;
}
